import random

#function for user to guess a number the computer has generated
def guess(num):
    #Initialize random_number variable to hold random number between 1 and what we pass through guess function
    random_number = random.randint(1, num)
    #Initialize guess variable to 0
    guess = 0
    #While guess is not equal to random_number
    while guess != random_number:
        #Prompt user to guess a number between 1 and the given number
        guess = int(input(f'Guess a number between 1 and {num}: '))
        #If the guessed number is less than our randomly generated number
        if guess < random_number:
            #Tell user the guess is too low, try again.
            print('Sorry, guess again. Too low')
            #if the guessed number is above the randomly generated number
        elif guess > random_number:
            #Tell the user the guess is too high and try again
            print('Sorry, guess again. Too high')
    #Once the user guesses the correct number tell them they win
    print(f'Yay, congrats. You have guess the number {random_number}')

#function for computer to guess a number the user has chosen
def computerGuess(num):
    #variable to hold lowest possible number to be generated by computer
    low = 1
    #variable to hold the highest possible number to be generated by computer
    high = num
    #variable to hold our feedback for the computer
    feedback = ''
    #while the feedback is not equal to "correct"
    while feedback != 'c':
        # if the lowest possible number is not equal to the highest possible number
        if low != high:
            # create the randomly generated number between the values we passed to low and high variables
            guess = random.randint(low, high)
        # if low is equal to high variable computer will guess the number we passed to low variable
        else:
            guess = low
        # ask user if the computer guess was higher, lower, or the same as their number
        feedback = input(f'Is {guess} too high (H), too low (L), or correct (C)?? ').lower()
        # if user inputs h for higher
        if feedback == 'h':
            # the computer guesses another random number minus one (updates high variable in guess calculations) 
            high = guess - 1
        # otherwise if user inputs l for lower
        elif feedback == 'l':
            # the computer guesses another random number plus one (updates low variable in guess calculations)
            low = guess + 1
    # Otherwise, if feedback from user is c for correct, let them know the computer guessed the right number!
    print(f'Yay! The computer guessed your number, {guess} , correctly!')

# calling computerGuess so computer will guess between 1-1000
computerGuess(1000)

# Computer will generate a random number between 1-1000 for user to guess.
# guess(1000)

